coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 0%

comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  hide_project_coverage: TRUE
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
