coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%

comment:
  layout: 'header, reach, diff, flags, files, tree, footer, feedback'
  hide_project_coverage: false
  behavior: new
  require_changes: false
  require_base: false
  require_head: true
