coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 0%

comment:
  layout: 'header, diff, files, footer'
  hide_project_coverage: false
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
