coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: auto
        threshold: 0%

comment:
  layout: "header, diff, changes, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
