name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.CI_DB_DATABASE }}
          MYSQL_USER: ${{ secrets.CI_DB_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Build Assets
        run: npm run build

      - name: Copy Environment File
        run: |
          cp .env.example .env
          cp .env.testing.ci .env.testing

      - name: Set Database Environment Variables
        run: |
          # Replace environment variables in .env.testing
          sed -i "s/\${CI_DB_CONNECTION}/${{ secrets.CI_DB_CONNECTION }}/g" .env.testing
          sed -i "s/\${CI_DB_HOST}/${{ secrets.CI_DB_HOST }}/g" .env.testing
          sed -i "s/\${CI_DB_PORT}/${{ secrets.CI_DB_PORT }}/g" .env.testing
          sed -i "s/\${CI_DB_DATABASE}/${{ secrets.CI_DB_DATABASE }}/g" .env.testing
          sed -i "s/\${CI_DB_USERNAME}/${{ secrets.CI_DB_USERNAME }}/g" .env.testing
          sed -i "s/\${CI_DB_PASSWORD}/${{ secrets.CI_DB_PASSWORD }}/g" .env.testing

      - name: Generate Application Key
        run: |
          php artisan key:generate
          php artisan key:generate --env=testing

      - name: Run Migrations
        run: php artisan migrate --env=testing

      - name: Tests
        run: |
          ./vendor/bin/pest --coverage-html coverage

      - name: Remove breadcrumb and links from HTML
        run: |
          # Remove breadcrumb navigation
          sed -i '/<nav aria-label="breadcrumb">/,/<\/nav>/d' coverage/index.html
          # Remove directory icons
          sed -i 's|<img src="_icons/[^"]*" class="octicon" />||g' coverage/index.html
          # Remove links but keep text
          sed -i 's|<a href="[^"]*">\([^<]*\)</a>|\1|g' coverage/index.html

      - name: Convert HTML to Markdown
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --to=gfm
            --output=coverage.md
            coverage/index.html

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.md
          # 検証のため最短期間で設定
          retention-days: 1

      - name: Add Coverage to Job Summary
        run: |
          echo "# Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat coverage.md >> $GITHUB_STEP_SUMMARY
